log:
  console:
    level: debug
db:
  driver: mysql
  user: root
  password: root123456
  name: ocihub
  server: localhost:3306
storageload: static
storage:
  filesystem:
    rootDirectory: /tmp/ocidata
